In [1]:
import numpy as np

Matrix adition

Two matrices can be added if they have same shape

In [2]:
#creating two matrices
A=np.array([[1,2],[4,5]])
B=np.array([[6,7],[8,9]])
print(A)
print(B)

[[1 2]
 [4 5]]
[[6 7]
 [8 9]]


In [3]:
A.shape

(2, 2)

In [4]:
B.shape

(2, 2)

Adding two matrices

In [5]:
sum=A+B

In [6]:
print(sum)

[[ 7  9]
 [12 14]]


In [8]:
#creating two matrices with random values
matrix_1=np.random.randint(10,size=(3,3))
matrix_2=np.random.randint(20,size=(3,3))

In [9]:
print(matrix_1)
print(matrix_2)

[[5 2 4]
 [4 5 8]
 [7 0 0]]
[[15  7  1]
 [ 4 17 19]
 [ 6 12  0]]


In [10]:
sum=matrix_1+matrix_2

In [12]:
print(sum)

[[20  9  5]
 [ 8 22 27]
 [13 12  0]]


Matrix subtraction

In [13]:
#creating two matrices
A=np.array([[1,2],[4,5]])
B=np.array([[6,7],[8,9]])
print(A)
print(B)

[[1 2]
 [4 5]]
[[6 7]
 [8 9]]


In [14]:
difference=A-B

In [15]:
print(difference)

[[-5 -5]
 [-4 -4]]


In [16]:
matrix_1=np.random.randint(10,size=(3,3))
matrix_2=np.random.randint(20,size=(3,3))
print(matrix_1)
print(matrix_2)

[[4 9 0]
 [0 5 1]
 [9 4 0]]
[[ 7 19 13]
 [ 9  3  4]
 [15  5 13]]


In [18]:
diff=np.subtract(matrix_1,matrix_2)
print(diff)

[[ -3 -10 -13]
 [ -9   2  -3]
 [ -6  -1 -13]]


Multiplying matrix by scalar

In [19]:
x=5
y=np.random.randint(10,size=(4,4))
print(y)

[[4 8 0 6]
 [6 7 7 1]
 [9 1 8 5]
 [8 7 9 6]]


In [20]:
product=np.multiply(x,y)
print(product)

[[20 40  0 30]
 [30 35 35  5]
 [45  5 40 25]
 [40 35 45 30]]


Multiplying two matrices

In [21]:
#create two matrices with random values
matrix_3=np.random.randint(5,size=(3,3))
matrix_4=np.random.randint(5,size=(3,4))
print(matrix_3)
print(matrix_4)

[[2 2 4]
 [0 2 4]
 [0 2 3]]
[[3 0 3 2]
 [3 2 1 0]
 [4 4 3 4]]


In [23]:
product=np.dot(matrix_3,matrix_4)
print(product)

[[28 20 20 20]
 [22 20 14 16]
 [18 16 11 12]]


In [24]:
product.shape

(3, 4)

**Element wise multiplication**

In [27]:
#create two matrices with random values
matrix_3=np.random.randint(5,size=(3,3))
matrix_4=np.random.randint(5,size=(3,3))

In [28]:
print(matrix_3)
print(matrix_4)

[[4 3 3]
 [3 4 3]
 [3 4 3]]
[[1 4 0]
 [2 4 4]
 [4 0 0]]


In [29]:
product=np.multiply(matrix_3,matrix_4)
print(product)

[[ 4 12  0]
 [ 6 16 12]
 [12  0  0]]
