In [1]:
import numpy as np


Creating matrix using numpy

In [2]:
matrix_1=np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [3]:
matrix_1.shape

(2, 2)

In [4]:
matrix_2=np.array([[10,35,45],[50,64,80],[20,40,98]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 40 98]]


In [5]:
matrix_2.shape

(3, 3)

Creating matrices with random value

In [6]:
random_matrix=np.random.rand(3,3)
print(random_matrix)

[[0.62219395 0.16642721 0.55658855]
 [0.49745308 0.42093288 0.38105354]
 [0.17038706 0.04375674 0.51846022]]


In [7]:
#creating matrix with random integers
random_integer_matrix=np.random.randint(100,size=(4,5))
print(random_integer_matrix)

[[43 14 92 42 54]
 [57 92  7 17 86]
 [57 92 82 12 34]
 [55 36 25 93 30]]


Matrix with all the values as 1

In [8]:
matrix_3=np.ones((5,5))
print(matrix_3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
matrix_3=np.ones((5,5),dtype=int)
print(matrix_3)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Null matrix or zero matrix

In [11]:
null_matrix=np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Identity matrix

In [13]:
identity_matrix=np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Transpose of a matrix

In [14]:
#matrix with random integer values
a=np.random.randint(100,size=(5,4))
print(a)

[[24 87 35 79]
 [84 52 94 23]
 [66 66 41 95]
 [75 13 26 73]
 [95 68 94 61]]


In [15]:
transpose_of_a=np.transpose(a)
print(transpose_of_a)

[[24 84 66 75 95]
 [87 52 66 13 68]
 [35 94 41 26 94]
 [79 23 95 73 61]]
